version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./acme_frontend
      dockerfile: Dockerfile
    volumes:
      - '/app/node_modules'
    ports:
      - 80:80
      - 443:443
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true 

  backend:
    restart: always
    container_name: backend
    build: ./acme_backend
    expose:
      - 5000
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
